{% set name = "graphql-core" %}
{% set version = "2.0" %}
{% set sha256 = "4830699be53f9154273fa15726fc8b0c90bc22bbb8fc7c932586503b3cb9330e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six >=1.10.0
    - promise >=2.0
    - rx >=1.6.0

test:
  imports:
    - graphql
    - graphql.error
    - graphql.execution
    - graphql.execution.executors
    - graphql.language
    - graphql.pyutils
    - graphql.type
    - graphql.utils
    - graphql.validation
    - graphql.validation.rules


about:
  home: https://github.com/graphql-python/graphql-core
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license: MIT
  license_family: MIT
  summary: 'GraphQL base implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-core

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
