travis:
  secure:
    BINSTAR_TOKEN: sYMEmZ7wotu8FxBtfLzbE9ORrebpevg/qlQXoUw0tTOIaxzgOie0TucFcWeBwNK2O5IeiWreqAs8sI6mTsr5KZVHVhv8UjrXkNpVvW4TxkgpVfc/mvrzjw/UG+wQaGr2lvrzbdTXJSOI4+QTq20NI1Ve7PC4XOGzui7KUaT62hjDO9Aez2bRLXforptxZmFdwy3Q+BltAZmKkKpvZK77eAnLe9/YSYY2y77ky/g/VMc02sw2OoNmY/9Jh0zyhxL3BGe4LYw7kZ9dwTARQ2DaHeso+dOrDpHUSlC981im/U0bP0NHqU/NA45x2SgP9ScGeoUm4wk02A6RkGf/YnjH8Jb0jo2AVQhmfVoGEHY/lRdxwLnl4YFYFwM+nO+9TE8OJ3b4FtfKZgSroM3MX0GMblD4rrjgnKZkanm7MbpgIVoL9xbDnNPJKlqhhAgny7YGXkohVVEwlvzAP7hi7NIqyruVtT7aY0SQr5RlThy3+/S8irkM1S9AveH72/x5/nnvEgvN6IzvBdkqBhCqat+NiHnr7Qd3CHlxih6kstSo6OAMZo6h2QjHhcZeer91Ls6EAVhSi3fh0FEyTc7mgEehEoo2kR1Z/JG6c9tQEtDnVkNVDx4CrcAADHVtEu0KKnx4ydExKOcu4vct80wmrEB6tVOFd8DWaOCYQ9r4awUrphE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
